server:
  context-path: /admin-service
  port: 80

spring:  
  datasource:
      url: jdbc:mysql://localhost/admin
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jpa:
    show-sql: true