server:
  context-path: /admin
  port: 9090
  
spring:  
  datasource:
      url: jdbc:mysql://localhost/admin-backend?characterEncoding=utf8&useSSL=true
      username: root
      password: root123 #123456
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jpa:
    show-sql: true
  redis:
    database: 0
    host: 10.48.172.45
    password: 
    port: 6379
    timeout: 0
    pool: 
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0  